// Daily affirmations, grouped by theme. "{name}" is replaced with the user's
// first name, or removed neatly if she hasn't given one.
window.BLOOM_AFFIRMATIONS = {
  self: [
    'I am worthy of the good things coming my way.',
    '{name}, you are enough exactly as you are today.',
    'I speak to myself with kindness and patience.',
    'My worth is not measured by my productivity.',
    'I trust myself to make good decisions.',
    'I am allowed to take up space.',
    '{name}, your softness is a strength.',
    'I am proud of the woman I am becoming.',
    'I deserve rest without guilt.',
    'I release the need to compare myself to others.',
    'My confidence grows every time I keep a promise to myself.',
    'I am beautiful in ways that have nothing to do with how I look.',
    'I choose to see myself the way the people who love me see me.',
    'You are allowed to outgrow old versions of yourself, {name}.',
    'I am becoming more comfortable being exactly who I am.',
    'My voice matters, and I use it.',
    "I forgive myself for what I didn't know before.",
    'I radiate warmth, and it comes back to me.',
    'I set boundaries that protect my peace.',
    '{name}, you light up the rooms you walk into.',
    'I am learning to love every chapter of my story.',
    "I don't need anyone's permission to shine.",
    'I honor my feelings without letting them run my day.',
    'I am a masterpiece and a work in progress at the same time.',
    'Today I will treat myself like someone I love.',
    'I trust the timing of my life.',
    'I am resilient. I have handled hard things before.',
    'My presence is a gift.',
    "I let go of what I can't control and focus on what I can.",
    "{name}, the world is better because you're in it.",
    "I am confident in who I am and who I'm becoming.",
    "I give myself credit for how far I've come.",
    'I am allowed to say no.',
    'My happiness matters, and I make room for it.',
    'I celebrate my small wins today.',
    'I attract people who value me.',
    'I am calm, capable, and in control of my choices.',
    'There is nobody else like me, and that is my power.',
    'I am gentle with myself on hard days.',
    '{name}, you are doing better than you think.',
  ],
  body: [
    "My body is strong, and I'm proud of every step.",
    'I move my body because I love it, not to punish it.',
    '{name}, every workout counts, even the short ones.',
    'I fuel my body with food that makes me feel good.',
    'Rest is part of my progress.',
    'I am getting stronger every single day.',
    'I listen to what my body needs today.',
    'Drinking water is an act of self-care.',
    'I show up for my health, even when motivation is low.',
    '{name}, your body has carried you through everything. Thank it today.',
    'Progress, not perfection.',
    'I feel energized and alive in my body.',
    'I choose movement that brings me joy.',
    'Sleep is my superpower, and I protect it.',
    'My health is an investment, not an expense.',
    'I am patient with my body as it changes and grows.',
    'Sweat today, glow tomorrow.',
    'I celebrate what my body can do.',
    '{name}, a ten-minute walk still counts as a win.',
    'I take a deep breath and let my shoulders relax.',
    'I nourish my body with kindness.',
    'Consistency beats intensity, and I am consistent.',
    'My body deserves care, not criticism.',
    'I am building habits my future self will thank me for.',
    'Every glass of water, every stretch, every step adds up.',
    'I am proud of myself for choosing health today.',
    '{name}, strong looks good on you.',
    'My mind and body are a team.',
    'I treat my body like my best friend.',
    'I make time for movement because I matter.',
    'I feel calm, grounded, and healthy.',
    'I am stronger than my excuses.',
    'Healthy choices come naturally to me.',
    '{name}, your effort today is planting seeds for tomorrow.',
    'I honor my body on low-energy days too.',
    'I am becoming the healthiest version of myself.',
    'My body is my home, and I take good care of it.',
    'I give my body the rest, water, and love it needs.',
    'Every day I move is a good day.',
    'I am grateful for my health and everything it lets me do.',
  ],
  money: [
    'I make smart choices with my money.',
    'Money flows to me in expected and unexpected ways.',
    '{name}, you are capable of building real wealth.',
    'I am in control of my finances.',
    'Every dollar I save is a gift to my future self.',
    'I deserve financial freedom, and I am working toward it.',
    'I spend with intention and save with purpose.',
    'I am learning more about money every day.',
    '{name}, your savings goals are closer than you think.',
    'I release shame around money and choose to grow.',
    'I am worthy of earning more.',
    'I know my value and I ask for it.',
    'My budget is a tool that gives me freedom.',
    "I am building a life I don't need a vacation from.",
    'Abundance is already finding its way to me.',
    'I am grateful for the money I have right now.',
    '{name}, checking your budget is an act of self-love.',
    'I am creating financial security for myself.',
    'Small savings add up to big dreams.',
    'I make money decisions from a place of calm, not fear.',
    'I can enjoy today and still plan for tomorrow.',
    'My income can grow, and I am open to new opportunities.',
    'I am the CEO of my own life.',
    '{name}, every smart money choice you make is building your future.',
    'I give myself permission to be wealthy.',
    'I pay myself first.',
    'I am proud of every bill I pay on time.',
    'Money is a tool, and I use it well.',
    'I attract opportunities that match my worth.',
    'I am disciplined with my spending, and it feels good.',
    '{name}, your future self is cheering you on.',
    'I believe I can reach every savings goal I set.',
    'I am open to receiving abundance in all its forms.',
    'Financial peace is possible for me.',
    'I am becoming a confident money manager.',
    'I choose long-term wins over short-term impulses.',
    'There is enough for me, and I am enough.',
    'I track my money because I care about my dreams.',
    '{name}, you are allowed to want more and go get it.',
    'Wealth begins with the habits I practice today.',
  ],
  goals: [
    'Small steps every day add up to big wins.',
    '{name}, discipline is just self-love with a plan.',
    'I keep the promises I make to myself.',
    'I do the hard thing first.',
    "I don't need to feel motivated to take action.",
    'I am focused on what matters most today.',
    'My goals are worth showing up for.',
    '{name}, you finish what you start.',
    'I am building momentum one choice at a time.',
    'Done is better than perfect.',
    'I am the kind of person who follows through.',
    'I trust the process, even when results are slow.',
    'Today I choose progress over excuses.',
    '{name}, today is a fresh page. Write something good.',
    'I am capable of achieving what I set my mind to.',
    'I break big dreams into small, doable steps.',
    "Every check mark is proof that I'm growing.",
    'I focus on my own lane.',
    '{name}, the future you who reached her goals is cheering you on.',
    "I don't wait for perfect timing. I start now.",
    'My habits shape my future, and I choose them wisely.',
    'I protect my time and energy for what matters.',
    'I am patient and persistent.',
    "Hard days don't erase my progress.",
    '{name}, you are closer than you were yesterday.',
    'I say yes to my goals and no to distractions.',
    'I can do anything for just ten minutes.',
    'I am proud of my consistency.',
    'Obstacles are part of my path, not the end of it.',
    "I show up for myself, even on days I don't feel like it.",
    '{name}, your dreams are valid and within reach.',
    'I set goals that excite me.',
    'Every day I get one step closer.',
    'I celebrate progress, no matter how small.',
    'I am focused, driven, and unstoppable.',
    'If I fall off track, I simply begin again.',
    '{name}, big things are coming. Keep going.',
    'I turn my plans into actions.',
    'My future is built by what I do today.',
    "I am becoming the woman I've always wanted to be.",
  ],
};
